### ISSUE TITLE
Which one is the official repo?

### ISSUE THREAD

**Issue by xuanqing94** [felix-laumann/Bayesian_CNN#3]
I noticed that there is another repo: https://github.com/kumar-shridhar/PyTorch-BayesianCNN

However, I cannot tell the difference (and both of them are in the author list of that paper?)

**Comment by kumar-shridhar** [comment]
Yes both of us are the authors and this repo of Felix is the stable version while the other one is more experimental (https://github.com/kumar-shridhar/PyTorch-BayesianCNN). This is the repo mentioned in the paper. 
Also, both repos are at the same stage and hence they look same but it wont be like that for long.
